# Versão do Ubuntu
dist: focal

# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.8"


addons:
  sonarcloud:
    organization: luizzenha-1
    token: ${SONAR_TOKEN}


jobs:
  include:
    - stage: Build & Tests
      name: "Unit Test, Quality & Security"

      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage

      # Defini o script de Teste que deve rodar toda vez que o código for alterado.
      script:
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;

    - stage: Stage Deploy
      name: "Deploy on heroku"
      script: skip
      
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        edge: true 
        app: devops-lab-zenha
        on:
            branch: main

    - stage: Stage Test
      name: GET URL stage
      script:
        - curl https://devops-lab-zenha.herokuapp.com/ | grep Hello || travis_terminate
    
    - stage: Production Deploy
      name: Google Api Engine
      script: skip

      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../gcpkey.json
        project: zenha-329914
        on:
          branch: main

    - stage: Production Test
      name: GET URL Production
      script:
        - curl https://zenha-329914.uc.r.appspot.com/ | grep Hello || travis_terminate 1;